@url = https://o7s04q5ub6.execute-api.us-east-1.amazonaws.com/prod/

# Realiza uma requisição GET para o endpoint '/empl' com um parâmetro 'id'
# Este endpoint provavelmente busca informações sobre um empregado específico pelo seu ID.
GET {{url}}/empl?id=2499ad26-ab10-4718-adb0-cf4e35d8ae11
###

# Realiza uma requisição POST para o endpoint '/empl'
# Esta requisição é usada para criar um novo registro de empregado.
# O corpo da requisição deve ser enviado no formato JSON conforme especificado abaixo.
POST {{url}}/empl
content-type: application/json

{
    "name": "Eiji",
    "position": "engineer"
}
###