@url = https://mhb546k8u9.execute-api.us-east-1.amazonaws.com/prod/

GET {{url}}/empl?id=5daac081-4770-4c46-9fe7-6a22d7dceab9
###

POST {{url}}/empl
content-type: application/json

{
    "name": "Eiji",
    "position": "engineer"
}
###