@url = https://mhb546k8u9.execute-api.us-east-1.amazonaws.com/prod/

# Realiza uma requisição GET para o endpoint '/empl' com um parâmetro 'id'
# Este endpoint provavelmente busca informações sobre um empregado específico pelo seu ID.
GET {{url}}/empl?id=5daac081-4770-4c46-9fe7-6a22d7dceab9
###

# Realiza uma requisição POST para o endpoint '/empl'
# Esta requisição é usada para criar um novo registro de empregado.
# O corpo da requisição deve ser enviado no formato JSON conforme especificado abaixo.
POST {{url}}/empl
content-type: application/json

{
    "name": "Eiji",  # Nome do empregado
    "position": "engineer"  # Posição ou cargo do empregado
}
###