@url = https://mrkoisp1fg.execute-api.us-east-1.amazonaws.com/prod/

# Realiza uma requisição GET para o endpoint '/empl' com um parâmetro 'id'
# Este endpoint provavelmente busca informações sobre um empregado específico pelo seu ID.
GET {{url}}/empl?id=b3bd3c8b-4bf3-4d09-ba7d-48c5322b62fa
###

# Realiza uma requisição POST para o endpoint '/empl'
# Esta requisição é usada para criar um novo registro de empregado.
# O corpo da requisição deve ser enviado no formato JSON conforme especificado abaixo.
POST {{url}}/empl
content-type: application/json

{
    "name": "Eiji",
    "position": "engineer"
}
###